# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: port_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='port_data.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fport_data.proto\"H\n\x04Ship\x12\x10\n\x08isInPort\x18\x01 \x01(\x08\x12\x0f\n\x07isEmpty\x18\x02 \x01(\x08\x12\x1d\n\x15remainingContainersNo\x18\x03 \x01(\r\"4\n\x0bStorageYard\x12\x14\n\x0c\x63ontainersNo\x18\x01 \x01(\r\x12\x0f\n\x07isEmpty\x18\x02 \x01(\x08\"\x8e\x02\n\x0cLoadingPoint\x12)\n\x02ID\x18\x01 \x01(\x0e\x32\x1d.LoadingPoint.LoadingPoint_ID\x12\x0c\n\x04\x62usy\x18\x02 \x01(\x08\"\xc4\x01\n\x0fLoadingPoint_ID\x12\n\n\x06SHIP_1\x10\x00\x12\n\n\x06SHIP_2\x10\x01\x12\n\n\x06SHIP_3\x10\x02\x12\x12\n\x0eSTORAGE_YARD_1\x10\x03\x12\x12\n\x0eSTORAGE_YARD_2\x10\x04\x12\x18\n\x14TRANSIT_POINT_AFRICA\x10\x05\x12\x18\n\x14TRANSIT_POINT_EUROPA\x10\x06\x12\x16\n\x12TRANSIT_POINT_ASIA\x10\x07\x12\x19\n\x15TRANSIT_POINT_AMERICA\x10\x08\"\x92\x01\n\x0cTransitPoint\x12!\n\x02ID\x18\x01 \x01(\x0e\x32\x15.TransitPoint.Port_ID\x12\x14\n\x0c\x63ontainersNo\x18\x02 \x01(\r\x12\x0f\n\x07isEmpty\x18\x03 \x01(\x08\"8\n\x07Port_ID\x12\n\n\x06\x41\x46RICA\x10\x00\x12\n\n\x06\x45UROPA\x10\x01\x12\x08\n\x04\x41SIA\x10\x02\x12\x0b\n\x07\x41MERICA\x10\x03\"\x8f\x01\n\tPortState\x12\x13\n\x04ship\x18\x01 \x01(\x0b\x32\x05.Ship\x12!\n\x0bstorageYard\x18\x02 \x01(\x0b\x32\x0c.StorageYard\x12$\n\rtransitPoints\x18\x03 \x03(\x0b\x32\r.TransitPoint\x12$\n\rloadingPoints\x18\x04 \x03(\x0b\x32\r.LoadingPoint'
)



_LOADINGPOINT_LOADINGPOINT_ID = _descriptor.EnumDescriptor(
  name='LoadingPoint_ID',
  full_name='LoadingPoint.LoadingPoint_ID',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SHIP_1', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHIP_2', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHIP_3', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STORAGE_YARD_1', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STORAGE_YARD_2', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRANSIT_POINT_AFRICA', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRANSIT_POINT_EUROPA', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRANSIT_POINT_ASIA', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRANSIT_POINT_AMERICA', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=222,
  serialized_end=418,
)
_sym_db.RegisterEnumDescriptor(_LOADINGPOINT_LOADINGPOINT_ID)

_TRANSITPOINT_PORT_ID = _descriptor.EnumDescriptor(
  name='Port_ID',
  full_name='TransitPoint.Port_ID',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AFRICA', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EUROPA', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ASIA', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AMERICA', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=511,
  serialized_end=567,
)
_sym_db.RegisterEnumDescriptor(_TRANSITPOINT_PORT_ID)


_SHIP = _descriptor.Descriptor(
  name='Ship',
  full_name='Ship',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isInPort', full_name='Ship.isInPort', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isEmpty', full_name='Ship.isEmpty', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='remainingContainersNo', full_name='Ship.remainingContainersNo', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=91,
)


_STORAGEYARD = _descriptor.Descriptor(
  name='StorageYard',
  full_name='StorageYard',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='containersNo', full_name='StorageYard.containersNo', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isEmpty', full_name='StorageYard.isEmpty', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=145,
)


_LOADINGPOINT = _descriptor.Descriptor(
  name='LoadingPoint',
  full_name='LoadingPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='LoadingPoint.ID', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='busy', full_name='LoadingPoint.busy', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LOADINGPOINT_LOADINGPOINT_ID,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=418,
)


_TRANSITPOINT = _descriptor.Descriptor(
  name='TransitPoint',
  full_name='TransitPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='TransitPoint.ID', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='containersNo', full_name='TransitPoint.containersNo', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isEmpty', full_name='TransitPoint.isEmpty', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRANSITPOINT_PORT_ID,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=421,
  serialized_end=567,
)


_PORTSTATE = _descriptor.Descriptor(
  name='PortState',
  full_name='PortState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ship', full_name='PortState.ship', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='storageYard', full_name='PortState.storageYard', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transitPoints', full_name='PortState.transitPoints', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loadingPoints', full_name='PortState.loadingPoints', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=570,
  serialized_end=713,
)

_LOADINGPOINT.fields_by_name['ID'].enum_type = _LOADINGPOINT_LOADINGPOINT_ID
_LOADINGPOINT_LOADINGPOINT_ID.containing_type = _LOADINGPOINT
_TRANSITPOINT.fields_by_name['ID'].enum_type = _TRANSITPOINT_PORT_ID
_TRANSITPOINT_PORT_ID.containing_type = _TRANSITPOINT
_PORTSTATE.fields_by_name['ship'].message_type = _SHIP
_PORTSTATE.fields_by_name['storageYard'].message_type = _STORAGEYARD
_PORTSTATE.fields_by_name['transitPoints'].message_type = _TRANSITPOINT
_PORTSTATE.fields_by_name['loadingPoints'].message_type = _LOADINGPOINT
DESCRIPTOR.message_types_by_name['Ship'] = _SHIP
DESCRIPTOR.message_types_by_name['StorageYard'] = _STORAGEYARD
DESCRIPTOR.message_types_by_name['LoadingPoint'] = _LOADINGPOINT
DESCRIPTOR.message_types_by_name['TransitPoint'] = _TRANSITPOINT
DESCRIPTOR.message_types_by_name['PortState'] = _PORTSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ship = _reflection.GeneratedProtocolMessageType('Ship', (_message.Message,), {
  'DESCRIPTOR' : _SHIP,
  '__module__' : 'port_data_pb2'
  # @@protoc_insertion_point(class_scope:Ship)
  })
_sym_db.RegisterMessage(Ship)

StorageYard = _reflection.GeneratedProtocolMessageType('StorageYard', (_message.Message,), {
  'DESCRIPTOR' : _STORAGEYARD,
  '__module__' : 'port_data_pb2'
  # @@protoc_insertion_point(class_scope:StorageYard)
  })
_sym_db.RegisterMessage(StorageYard)

LoadingPoint = _reflection.GeneratedProtocolMessageType('LoadingPoint', (_message.Message,), {
  'DESCRIPTOR' : _LOADINGPOINT,
  '__module__' : 'port_data_pb2'
  # @@protoc_insertion_point(class_scope:LoadingPoint)
  })
_sym_db.RegisterMessage(LoadingPoint)

TransitPoint = _reflection.GeneratedProtocolMessageType('TransitPoint', (_message.Message,), {
  'DESCRIPTOR' : _TRANSITPOINT,
  '__module__' : 'port_data_pb2'
  # @@protoc_insertion_point(class_scope:TransitPoint)
  })
_sym_db.RegisterMessage(TransitPoint)

PortState = _reflection.GeneratedProtocolMessageType('PortState', (_message.Message,), {
  'DESCRIPTOR' : _PORTSTATE,
  '__module__' : 'port_data_pb2'
  # @@protoc_insertion_point(class_scope:PortState)
  })
_sym_db.RegisterMessage(PortState)


# @@protoc_insertion_point(module_scope)
