# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: port_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='port_data.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fport_data.proto\"7\n\x04Ship\x12\x10\n\x08isInPort\x18\x01 \x01(\x08\x12\x1d\n\x15remainingContainersNo\x18\x02 \x01(\r\"#\n\x0bStorageYard\x12\x14\n\x0c\x63ontainersNo\x18\x01 \x01(\r\"\x81\x01\n\x0cTransitPoint\x12!\n\x02ID\x18\x01 \x01(\x0e\x32\x15.TransitPoint.Port_ID\x12\x14\n\x0c\x63ontainersNo\x18\x02 \x01(\r\"8\n\x07Port_ID\x12\n\n\x06\x41\x46RICA\x10\x00\x12\n\n\x06\x45UROPA\x10\x01\x12\x08\n\x04\x41SIA\x10\x02\x12\x0b\n\x07\x41MERICA\x10\x03\"\xe1\x02\n\x04\x43\x61rt\x12\x15\n\rwithContainer\x18\x02 \x01(\x08\x12#\n\x07\x63\x61rtPos\x18\x03 \x01(\x0e\x32\x12.Cart.CartPosition\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x10\n\x08targetID\x18\x05 \x01(\r\"\xfc\x01\n\x0c\x43\x61rtPosition\x12\r\n\tAFRICA_LP\x10\x00\x12\x12\n\x0e\x41\x46RICA_WAITING\x10\x01\x12\r\n\tEUROPA_LP\x10\x02\x12\x12\n\x0e\x45UROPA_WAITING\x10\x03\x12\x0b\n\x07\x41SIA_LP\x10\x04\x12\x10\n\x0c\x41SIA_WAITING\x10\x05\x12\x0e\n\nAMERICA_LP\x10\x06\x12\x13\n\x0f\x41MERICA_WAITING\x10\x07\x12\n\n\x06ST_LP1\x10\x08\x12\n\n\x06ST_LP2\x10\t\x12\x0e\n\nST_WAITING\x10\n\x12\x0c\n\x08SHIP_LP1\x10\x0b\x12\x0c\n\x08SHIP_LP2\x10\x0c\x12\x0c\n\x08SHIP_LP3\x10\r\x12\x10\n\x0cSHIP_WAITIMG\x10\x0e\"&\n\x05\x43rane\x12\x0f\n\x07isReady\x18\x01 \x01(\x08\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x7f\n\tPortState\x12\x13\n\x04ship\x18\x01 \x01(\x0b\x32\x05.Ship\x12!\n\x0bstorageYard\x18\x02 \x01(\x0b\x32\x0c.StorageYard\x12$\n\rtransitPoints\x18\x03 \x03(\x0b\x32\r.TransitPoint\x12\x14\n\x05\x63\x61rts\x18\x04 \x03(\x0b\x32\x05.Cart'
)



_TRANSITPOINT_PORT_ID = _descriptor.EnumDescriptor(
  name='Port_ID',
  full_name='TransitPoint.Port_ID',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AFRICA', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EUROPA', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ASIA', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AMERICA', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=187,
  serialized_end=243,
)
_sym_db.RegisterEnumDescriptor(_TRANSITPOINT_PORT_ID)

_CART_CARTPOSITION = _descriptor.EnumDescriptor(
  name='CartPosition',
  full_name='Cart.CartPosition',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AFRICA_LP', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AFRICA_WAITING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EUROPA_LP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EUROPA_WAITING', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ASIA_LP', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ASIA_WAITING', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AMERICA_LP', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AMERICA_WAITING', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ST_LP1', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ST_LP2', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ST_WAITING', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHIP_LP1', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHIP_LP2', index=12, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHIP_LP3', index=13, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHIP_WAITIMG', index=14, number=14,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=347,
  serialized_end=599,
)
_sym_db.RegisterEnumDescriptor(_CART_CARTPOSITION)


_SHIP = _descriptor.Descriptor(
  name='Ship',
  full_name='Ship',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isInPort', full_name='Ship.isInPort', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='remainingContainersNo', full_name='Ship.remainingContainersNo', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=74,
)


_STORAGEYARD = _descriptor.Descriptor(
  name='StorageYard',
  full_name='StorageYard',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='containersNo', full_name='StorageYard.containersNo', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=111,
)


_TRANSITPOINT = _descriptor.Descriptor(
  name='TransitPoint',
  full_name='TransitPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='TransitPoint.ID', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='containersNo', full_name='TransitPoint.containersNo', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRANSITPOINT_PORT_ID,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=243,
)


_CART = _descriptor.Descriptor(
  name='Cart',
  full_name='Cart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='withContainer', full_name='Cart.withContainer', index=0,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cartPos', full_name='Cart.cartPos', index=1,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='Cart.name', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='targetID', full_name='Cart.targetID', index=3,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CART_CARTPOSITION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=599,
)


_CRANE = _descriptor.Descriptor(
  name='Crane',
  full_name='Crane',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isReady', full_name='Crane.isReady', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='Crane.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=601,
  serialized_end=639,
)


_PORTSTATE = _descriptor.Descriptor(
  name='PortState',
  full_name='PortState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ship', full_name='PortState.ship', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='storageYard', full_name='PortState.storageYard', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transitPoints', full_name='PortState.transitPoints', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='carts', full_name='PortState.carts', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=641,
  serialized_end=768,
)

_TRANSITPOINT.fields_by_name['ID'].enum_type = _TRANSITPOINT_PORT_ID
_TRANSITPOINT_PORT_ID.containing_type = _TRANSITPOINT
_CART.fields_by_name['cartPos'].enum_type = _CART_CARTPOSITION
_CART_CARTPOSITION.containing_type = _CART
_PORTSTATE.fields_by_name['ship'].message_type = _SHIP
_PORTSTATE.fields_by_name['storageYard'].message_type = _STORAGEYARD
_PORTSTATE.fields_by_name['transitPoints'].message_type = _TRANSITPOINT
_PORTSTATE.fields_by_name['carts'].message_type = _CART
DESCRIPTOR.message_types_by_name['Ship'] = _SHIP
DESCRIPTOR.message_types_by_name['StorageYard'] = _STORAGEYARD
DESCRIPTOR.message_types_by_name['TransitPoint'] = _TRANSITPOINT
DESCRIPTOR.message_types_by_name['Cart'] = _CART
DESCRIPTOR.message_types_by_name['Crane'] = _CRANE
DESCRIPTOR.message_types_by_name['PortState'] = _PORTSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ship = _reflection.GeneratedProtocolMessageType('Ship', (_message.Message,), {
  'DESCRIPTOR' : _SHIP,
  '__module__' : 'port_data_pb2'
  # @@protoc_insertion_point(class_scope:Ship)
  })
_sym_db.RegisterMessage(Ship)

StorageYard = _reflection.GeneratedProtocolMessageType('StorageYard', (_message.Message,), {
  'DESCRIPTOR' : _STORAGEYARD,
  '__module__' : 'port_data_pb2'
  # @@protoc_insertion_point(class_scope:StorageYard)
  })
_sym_db.RegisterMessage(StorageYard)

TransitPoint = _reflection.GeneratedProtocolMessageType('TransitPoint', (_message.Message,), {
  'DESCRIPTOR' : _TRANSITPOINT,
  '__module__' : 'port_data_pb2'
  # @@protoc_insertion_point(class_scope:TransitPoint)
  })
_sym_db.RegisterMessage(TransitPoint)

Cart = _reflection.GeneratedProtocolMessageType('Cart', (_message.Message,), {
  'DESCRIPTOR' : _CART,
  '__module__' : 'port_data_pb2'
  # @@protoc_insertion_point(class_scope:Cart)
  })
_sym_db.RegisterMessage(Cart)

Crane = _reflection.GeneratedProtocolMessageType('Crane', (_message.Message,), {
  'DESCRIPTOR' : _CRANE,
  '__module__' : 'port_data_pb2'
  # @@protoc_insertion_point(class_scope:Crane)
  })
_sym_db.RegisterMessage(Crane)

PortState = _reflection.GeneratedProtocolMessageType('PortState', (_message.Message,), {
  'DESCRIPTOR' : _PORTSTATE,
  '__module__' : 'port_data_pb2'
  # @@protoc_insertion_point(class_scope:PortState)
  })
_sym_db.RegisterMessage(PortState)


# @@protoc_insertion_point(module_scope)
